### ISSUE TITLE
How to handle different versions of the AllergyIntolerance profile? (Question by Brecht Van Vooren: Vitalink)

### ISSUE THREAD

**Issue by bdc-ehealth** [ehealthplatformstandards/BelgianProfileVersioningStrategy#1]
Question originally asked to eHealth: https://be-ehealth-standards.atlassian.net/jira/servicedesk/projects/ESI/queues/custom/20/ESI-165 @smals-bvv 

There is a proposal of solution based on the Vitalink/UHMEP needs and we solicit further input. The proposal is described in this Google doc document: https://docs.google.com/document/d/1NIaq6NfqrfK46tRTlcGlWEFRrbCzg5uZrs6cgoWZcUs/edit

**Comment by bdc-ehealth** [comment]
@smals-bvv  (mail by Brecht Van Vooren on 28/06/2023) met een aantal bijkomende vragen over het document.

[FHIRSRV-VersioningStrategyonProfilelevel-280623-1131-141.pdf](https://github.com/ehealthplatformstandards/BelgianProfileVersioningStrategy/files/11893864/FHIRSRV-VersioningStrategyonProfilelevel-280623-1131-141.pdf)

**Comment by bdc-ehealth** [comment]
@ipollet Si je veux discuter ces items-ci avec un specialiste FHIR de RSW, qui dois-je inviter?
@fdetaver , idem pour BruSafe, c'est toi?

**Comment by fdetaver** [comment]
C'est bien pour moi pour l'instant.

**Comment by ipollet** [comment]
Je vois ça en interne et je reviens vers vous. Ca ne devrait pas être moi mais il faudra me laisser dans les boucles pour suivi.

**Comment by ipollet** [comment]
Bonjour Bart,
Les personnes à impliquer chez nous sont : Nabil Hammoud, Micaël Rondelez et Didier Témans.
Come indiqué avant, me laisser dans les boucles pour le suivi même si je ne participe pas nécessairement aux réunions techniques.
Bàt,

**Comment by bdc-ehealth** [comment]
All issues regarding this point have been solved in #7.
