### ISSUE TITLE
Is the profile something we can require?

### ISSUE THREAD

**Issue by bdc-ehealth** [ehealthplatformstandards/BelgianProfileVersioningStrategy#3]
from #1 @smals-bvv 
By defining only one endpoint for each resource type we need know the profile and version of the profile for when a client retrieves the
information back later in time (when profiles and versions might have changed).

**Comment by ehealthplatformstandards** [comment]
@smals-bvv : this is a very interesting conversation, you should really read it:

https://chat.fhir.org/#narrow/stream/179247-Security-and-Privacy/topic/Progress.20on.20digital.20signatures.20and.20integrity

**Comment by bdc-ehealth** [comment]
According to HL7 international, we cannot require the profile (at least they discourage it strongly). In #7 we decided not to interfere with metadata.profile , and create our own extension instead.
